name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  nuts:
    needs: unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
  # conditional nuts based on commit message includes a certain string
  sandbox-nuts:
    needs: [nuts, unit-tests]
    if: contains(github.event.push.head_commit.message,'[sb-nuts]')
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    with:
      command: test:nuts:sandbox
      os: ubuntu-latest
